import { AntdRegistry } from "@ant-design/nextjs-registry";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals";
import "./globals.css";
import { MqttProvider } from "./providers/mqtt";
import { TanstackProvider } from "./providers/tanstack-provider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AntdRegistry>
          <TanstackProvider>
            <MqttProvider
              brokerUrl="ws://broker.emqx.io:8083/mqtt"
              options={{
                username: 'NAlisson',
                password: 'Nathiele',
              }}
            >
              {children}
            </MqttProvider>
          </TanstackProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
